# Generated by Django 4.2.7 on 2023-11-18 15:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_expense_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="family",
            table="family",
        ),
    ]
